### PR TITLE
Remove method_missing magic

### PR DESCRIPTION
**Pull request by johnnyshields**
- Remove method_missing magic and replace with explicitly defined dynamic methods. This way the methods will show up in "Did you mean?" and it's just generally better/cleaner to do it this way.
- "#{attr}_#{locale}" methods (e.g. name_en) can now handle any locale format, e.g. name in zh-CN becomes "name_zhcn" (downcased and with hyphens removed). The key "zh-CN" will be used in the database. (The current code can only handle locales which are two lowercase alpha characters.)
- "#{attr}_#{locale}" methods (e.g. name_en) should NOT use I18n fallbacks. The reason for doing this is so that they can be used in forms. They should be equivalent to name['en']
- Smaller changes:
   - `#json_translate_fallback_locales` should always return an array (as the method name is plural)
   - In `#read_json_translation`, `I18n.interpolate` should only be called if `params` parameter is present as `begin/rescue` is slow and rarely used (as `params` is usually not present)

### CODE REVIEW

**Comment by johnnyshields** [comment]
@cfabianski please take a look

**Comment by cfabianski** [comment]
Hi @johnnyshields, thanks for uour contribution. 
I’ll have a look soon. In the meantime, could you please have a look at the build or maybe open another PR to address the latest commit?

Ta

**Comment by johnnyshields** [comment]
@cfabianski mysql is passing but pg is not due to the recently release 1.0.0 version of pg. I have set pg "< 1.0.0" in the project's Gemfile (not the gempsec) in order to get the tests to pass.

**Comment by johnnyshields** [comment]
@cfabianski can you please take a look at this?

**Comment by johnnyshields** [comment]
@cfabianski can you please take a look at this?

**Comment by cfabianski** [comment]
@johnnyshields Thanks very much. I'll have a quick look at what is happening with the latest version of PG and I'll get back to you.

**Comment by cfabianski** [comment]
I'll try to release another version of the gem (it will be a major version change) by today. 
Thanks for your patience :)

**Comment by johnnyshields** [comment]
@cfabianski thank you very much for this!

**Pull request merged**
